# Generated by Django 3.2.7 on 2021-09-16 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=60)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('quota', models.IntegerField()),
                ('student', models.ManyToManyField(blank=True, related_name='subject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
