# Generated by Django 3.2.7 on 2021-09-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=60)),
                ('last', models.CharField(max_length=60)),
                ('courses', models.ManyToManyField(blank=True, related_name='student', to='courses.Course')),
            ],
        ),
    ]
