# Generated by Django 3.2.7 on 2021-09-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210916_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrant',
            old_name='courses',
            new_name='courset',
        ),
    ]
