# Generated by Django 3.2.7 on 2021-10-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='quota',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
