# Generated by Django 3.2.7 on 2021-09-13 16:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=60)),
                ('subject_semester', models.IntegerField()),
                ('subject_year', models.IntegerField()),
                ('subject_quota', models.IntegerField()),
                ('student', models.ManyToManyField(blank=True, related_name='subject', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
